/*
 * PWA API
 * PWA API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.sincon.sigeo.dto;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import it.sincon.sigeo.enums.GestioneLingua;

/**
 * CanaleVeicolazioneDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-15T12:03:22.432+02:00")
public class CanaleVeicolazioneDTO implements Serializable{
  
  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

  private Boolean visibilita;
  
  private Boolean attivo = null;

  private Boolean cancellabile = null;

  
  private String descrizione = null;

  
  private List<CampoCanaleVeicolazioneDTO> elencoCampi = new ArrayList<>();

  
  private GestioneLingua gestioneLingua = null;

  private Long id = null;

  public CanaleVeicolazioneDTO attivo(Boolean attivo) {
    this.attivo = attivo;
    return this;
  }

   /**
   * Get attivo
   * @return attivo
  **/
  
  public Boolean isAttivo() {
    return attivo;
  }

  public void setAttivo(Boolean attivo) {
    this.attivo = attivo;
  }

  public CanaleVeicolazioneDTO cancellabile(Boolean cancellabile) {
    this.cancellabile = cancellabile;
    return this;
  }

   /**
   * Get cancellabile
   * @return cancellabile
  **/

  public Boolean isCancellabile() {
    return cancellabile;
  }

  public void setCancellabile(Boolean cancellabile) {
    this.cancellabile = cancellabile;
  }

  public CanaleVeicolazioneDTO descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Get descrizione
   * @return descrizione
  **/

  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }


  public Boolean getVisibilita() {
	  return visibilita;
  }
	
  public void setVisibilita(Boolean visibilita) {
	  this.visibilita = visibilita;
  }

  public List<CampoCanaleVeicolazioneDTO> getElencoCampi() {
	  return elencoCampi;
  }

  public void setElencoCampi(List<CampoCanaleVeicolazioneDTO> elencoCampi) {
	  this.elencoCampi = elencoCampi;
  }

public CanaleVeicolazioneDTO gestioneLingua(GestioneLingua gestioneLingua) {
    this.gestioneLingua = gestioneLingua;
    return this;
  }

   /**
   * Get gestioneLingua
   * @return gestioneLingua
  **/

  public GestioneLingua getGestioneLingua() {
    return gestioneLingua;
  }

  public void setGestioneLingua(GestioneLingua gestioneLingua) {
    this.gestioneLingua = gestioneLingua;
  }

  public CanaleVeicolazioneDTO id(Long id) {
    this.id = id;
    return this;
  }

  public Boolean getAttivo() {
	return attivo;
}

  public Boolean getCancellabile() {
	return cancellabile;
  }

   /**
   * Get id
   * @return id
  **/
  
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CanaleVeicolazioneDTO canaleVeicolazioneDTO = (CanaleVeicolazioneDTO) o;
    return Objects.equals(this.attivo, canaleVeicolazioneDTO.attivo) &&
        Objects.equals(this.cancellabile, canaleVeicolazioneDTO.cancellabile) &&
        Objects.equals(this.descrizione, canaleVeicolazioneDTO.descrizione) &&
        Objects.equals(this.elencoCampi, canaleVeicolazioneDTO.elencoCampi) &&
        Objects.equals(this.gestioneLingua, canaleVeicolazioneDTO.gestioneLingua) &&
        Objects.equals(this.id, canaleVeicolazioneDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attivo, cancellabile, descrizione, elencoCampi, gestioneLingua, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CanaleVeicolazioneDTO {\n");
    
    sb.append("    attivo: ").append(toIndentedString(attivo)).append("\n");
    sb.append("    cancellabile: ").append(toIndentedString(cancellabile)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    elencoCampi: ").append(toIndentedString(elencoCampi)).append("\n");
    sb.append("    gestioneLingua: ").append(toIndentedString(gestioneLingua)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

