/*
 * PWA API
 * PWA API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.sincon.sigeo.dto;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import it.sincon.sigeo.enums.JoinOperator;

/**
 * FilterGroup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-15T12:03:22.432+02:00")
public class FilterGroup {
  
  private List<Filter> filters = null;

  
  private List<FilterGroup> groups = null;

  /**
   * Gets or Sets joinOperator
   */

  
  private JoinOperator joinOperator = null;

  public FilterGroup filters(List<Filter> filters) {
    this.filters = filters;
    return this;
  }

  public FilterGroup addFiltersItem(Filter filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  
  public List<Filter> getFilters() {
    return filters;
  }

  public void setFilters(List<Filter> filters) {
    this.filters = filters;
  }

  public FilterGroup groups(List<FilterGroup> groups) {
    this.groups = groups;
    return this;
  }

  public FilterGroup addGroupsItem(FilterGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  
  public List<FilterGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<FilterGroup> groups) {
    this.groups = groups;
  }

  public FilterGroup joinOperator(JoinOperator joinOperator) {
    this.joinOperator = joinOperator;
    return this;
  }

   /**
   * Get joinOperator
   * @return joinOperator
  **/
  
  public JoinOperator getJoinOperator() {
    return joinOperator;
  }

  public void setJoinOperator(JoinOperator joinOperator) {
    this.joinOperator = joinOperator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterGroup filterGroup = (FilterGroup) o;
    return Objects.equals(this.filters, filterGroup.filters) &&
        Objects.equals(this.groups, filterGroup.groups) &&
        Objects.equals(this.joinOperator, filterGroup.joinOperator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filters, groups, joinOperator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterGroup {\n");
    
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    joinOperator: ").append(toIndentedString(joinOperator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

