/*
 * PWA API
 * PWA API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.sincon.sigeo.dto;

import java.io.Serializable;
import java.util.Objects;
import java.util.Set;

/**
 * MenuListaValoriDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-15T12:03:22.432+02:00")
public class MenuListaValoriDTO implements Serializable {
  
  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


  private Set<MenuListaValoriDTO> child = null;

  
  private Boolean configurabile = null;

  
  private String descrizione = null;

  
  private String id = null;



   /**
   * Get child
   * @return child
  **/
  


  public MenuListaValoriDTO configurabile(Boolean configurabile) {
    this.configurabile = configurabile;
    return this;
  }

   public Set<MenuListaValoriDTO> getChild() {
	   return child;
   }

	public void setChild(Set<MenuListaValoriDTO> child) {
		this.child = child;
	}

/**
   * Get configurabile
   * @return configurabile
  **/
  
  public Boolean isConfigurabile() {
    return configurabile;
  }
  
  public Boolean getConfigurabile() {
	return configurabile;
 }

public void setConfigurabile(Boolean configurabile) {
    this.configurabile = configurabile;
  }

  public MenuListaValoriDTO descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Get descrizione
   * @return descrizione
  **/

  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }

  public MenuListaValoriDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuListaValoriDTO menuListaValoriDTO = (MenuListaValoriDTO) o;
    return Objects.equals(this.child, menuListaValoriDTO.child) &&
        Objects.equals(this.configurabile, menuListaValoriDTO.configurabile) &&
        Objects.equals(this.descrizione, menuListaValoriDTO.descrizione) &&
        Objects.equals(this.id, menuListaValoriDTO.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(child, configurabile, descrizione, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuListaValoriDTO {\n");
    
    sb.append("    child: ").append(toIndentedString(child)).append("\n");
    sb.append("    configurabile: ").append(toIndentedString(configurabile)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

