/*
 * PWA API
 * PWA API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.sincon.sigeo.dto;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchResponseOfobject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-15T12:03:22.432+02:00")
public class SearchResponse<T> {
  
  private List<T> items = null;

  
  private Integer pageItemsNumber = null;

  
  private Integer pageNumber = null;

  
  private Integer pageSize = null;

  
  private Long totalItems = null;

  
  private Integer totalPages = null;

  public SearchResponse<T> items(List<T> items) {
    this.items = items;
    return this;
  }

  public SearchResponse<T> addItemsItem(T itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  
  public List<T> getItems() {
    return items;
  }

  public void setItems(List<T> items) {
    this.items = items;
  }

  public SearchResponse<T> pageItemsNumber(Integer pageItemsNumber) {
    this.pageItemsNumber = pageItemsNumber;
    return this;
  }

   /**
   * Get pageItemsNumber
   * @return pageItemsNumber
  **/
  
  public Integer getPageItemsNumber() {
    return pageItemsNumber;
  }

  public void setPageItemsNumber(Integer pageItemsNumber) {
    this.pageItemsNumber = pageItemsNumber;
  }

  public SearchResponse<T> pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public SearchResponse<T> pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public SearchResponse<T> totalItems(Long totalItems) {
    this.totalItems = totalItems;
    return this;
  }

   /**
   * Get totalItems
   * @return totalItems
  **/
  
  public Long getTotalItems() {
    return totalItems;
  }

  public void setTotalItems(Long totalItems) {
    this.totalItems = totalItems;
  }

  public SearchResponse<T> totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  
  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }


  @SuppressWarnings("unchecked")
@Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse<T> searchResponseOfobject = (SearchResponse<T>) o;
    return Objects.equals(this.items, searchResponseOfobject.items) &&
        Objects.equals(this.pageItemsNumber, searchResponseOfobject.pageItemsNumber) &&
        Objects.equals(this.pageNumber, searchResponseOfobject.pageNumber) &&
        Objects.equals(this.pageSize, searchResponseOfobject.pageSize) &&
        Objects.equals(this.totalItems, searchResponseOfobject.totalItems) &&
        Objects.equals(this.totalPages, searchResponseOfobject.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, pageItemsNumber, pageNumber, pageSize, totalItems, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseOfobject {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    pageItemsNumber: ").append(toIndentedString(pageItemsNumber)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

