/*
 * PWA API
 * PWA API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.sincon.sigeo.dto;

import java.time.Instant;
import java.util.List;

/**
 * UserDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-09-15T12:03:22.432+02:00")
public class UserDTO {
  
  private Boolean activated = null;

  
  private List<String> authorities = null;

  
  private CanaleVeicolazioneDTO canaleVeicolazioneDTO = null;

  
  private String cap = null;

  
  private String cellphone = null;

  
  private String codiceFiscale = null;

  
  private String comune = null;

  
  private String createdBy = null;

  
  private String createdDate = null;

  
  private String email = null;

  
  private String firstName = null;

  
  private List<AuthorityDTO> fullauthorities = null;

  
  private Long id = null;

  
  private String imageUrl = null;

  
  private String indirizzo = null;

  
  private String langKey = null;

  
  private String lastModifiedBy = null;

  
  private String lastModifiedDate = null;

  
  private String lastName = null;

  
  private String login = null;


  public Boolean getActivated() {
	return activated;
}

public void setActivated(Boolean activated) {
	this.activated = activated;
}

public List<String> getAuthorities() {
	return authorities;
}

public void setAuthorities(List<String> authorities) {
	this.authorities = authorities;
}

public CanaleVeicolazioneDTO getCanaleVeicolazioneDTO() {
	return canaleVeicolazioneDTO;
}

public void setCanaleVeicolazioneDTO(CanaleVeicolazioneDTO canaleVeicolazioneDTO) {
	this.canaleVeicolazioneDTO = canaleVeicolazioneDTO;
}

public String getCap() {
	return cap;
}

public void setCap(String cap) {
	this.cap = cap;
}

public String getCellphone() {
	return cellphone;
}

public void setCellphone(String cellphone) {
	this.cellphone = cellphone;
}

public String getCodiceFiscale() {
	return codiceFiscale;
}

public void setCodiceFiscale(String codiceFiscale) {
	this.codiceFiscale = codiceFiscale;
}

public String getComune() {
	return comune;
}

public void setComune(String comune) {
	this.comune = comune;
}

public String getCreatedBy() {
	return createdBy;
}

public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
}

public String getCreatedDate() {
	return createdDate;
}

public void setCreatedDate(String createdDate) {
	this.createdDate = createdDate;
}

public String getEmail() {
	return email;
}

public void setEmail(String email) {
	this.email = email;
}

public String getFirstName() {
	return firstName;
}

public void setFirstName(String firstName) {
	this.firstName = firstName;
}

public List<AuthorityDTO> getFullauthorities() {
	return fullauthorities;
}

public void setFullauthorities(List<AuthorityDTO> fullauthorities) {
	this.fullauthorities = fullauthorities;
}

public Long getId() {
	return id;
}

public void setId(Long id) {
	this.id = id;
}

public String getImageUrl() {
	return imageUrl;
}

public void setImageUrl(String imageUrl) {
	this.imageUrl = imageUrl;
}

public String getIndirizzo() {
	return indirizzo;
}

public void setIndirizzo(String indirizzo) {
	this.indirizzo = indirizzo;
}

public String getLangKey() {
	return langKey;
}

public void setLangKey(String langKey) {
	this.langKey = langKey;
}

public String getLastModifiedBy() {
	return lastModifiedBy;
}

public void setLastModifiedBy(String lastModifiedBy) {
	this.lastModifiedBy = lastModifiedBy;
}

public String getLastModifiedDate() {
	return lastModifiedDate;
}

public void setLastModifiedDate(String lastModifiedDate) {
	this.lastModifiedDate = lastModifiedDate;
}

public String getLastName() {
	return lastName;
}

public void setLastName(String lastName) {
	this.lastName = lastName;
}

public String getLogin() {
	return login;
}

public void setLogin(String login) {
	this.login = login;
}


}

