package it.sincon.sigeo.enums;

public enum FilterCondition {

	NOT_EMPTY, LESSER_OR_EQUALS, NOT_LIKE, LESSER, LIKE_IGNORECASE, NOT_EQUALS, ENDS_WITH, STARTS_WITH_IGNORE_CASE, NOT_NULL, STARTS_WITH, GREATER_OR_EQUALS, CONCAT_CONTAINS_IGNORECASE, IS_EMPTY, GREATER, IS_NULL, EQUALS, CONTAINS_IGNORECASE, ENDS_WITH_IGNORE_CASE, LIKE, CONTAINS;

}
